spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/appnotes_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appnotes_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:appnotes_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}